/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RaboCurrencyInput {
        "currency": string;
        "separator": string;
    }
}
declare global {
    interface HTMLRaboCurrencyInputElement extends Components.RaboCurrencyInput, HTMLStencilElement {
    }
    var HTMLRaboCurrencyInputElement: {
        prototype: HTMLRaboCurrencyInputElement;
        new (): HTMLRaboCurrencyInputElement;
    };
    interface HTMLElementTagNameMap {
        "rabo-currency-input": HTMLRaboCurrencyInputElement;
    }
}
declare namespace LocalJSX {
    interface RaboCurrencyInput {
        "currency"?: string;
        "onHandleSubmit"?: (event: CustomEvent<number>) => void;
        "separator"?: string;
    }
    interface IntrinsicElements {
        "rabo-currency-input": RaboCurrencyInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rabo-currency-input": LocalJSX.RaboCurrencyInput & JSXBase.HTMLAttributes<HTMLRaboCurrencyInputElement>;
        }
    }
}
